"""add follow

Revision ID: 04361f8a9892
Revises: 220cfe2cf092
Create Date: 2022-02-18 15:51:31.734368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04361f8a9892'
down_revision = '220cfe2cf092'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
