"""about me and last seen

Revision ID: 220cfe2cf092
Revises: 6c375dc36cd8
Create Date: 2022-02-15 11:44:11.262505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '220cfe2cf092'
down_revision = '6c375dc36cd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('users', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_seen')
    op.drop_column('users', 'about_me')
    # ### end Alembic commands ###
