"""change avatar

Revision ID: 6c375dc36cd8
Revises: a9e1cb173b2b
Create Date: 2022-02-15 10:57:02.276266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c375dc36cd8'
down_revision = 'a9e1cb173b2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('real_avatar', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'real_avatar')
    # ### end Alembic commands ###
